### ISSUE TITLE
create script failure when multiple network interfaces are requested

### ISSUE THREAD

**Issue by dannyman** [neicnordic/ganeti-os-nocloud#4]
This is not urgent for us, as the workaround is to create an instance with one interface, and then manually add additional interfaces via `gnt-instance modify --net add` and edit `/etc/netplan/50-cloud-init.yaml` but I thought I would "kick the tires" here. It looks like the `create` script wants to handle multiple nics but something is wrong here, and there may be an easy fix?

```
> sudo gnt-instance add -s 16G --no-wait-for-sync -B memory=4G,vcpus=2 -o nocloud+ubuntu-20.04 -O dns_nameservers=10.10.1.1,dns_search=site.qxxxxxxxd.com --net 0:network=site,ip=10.10.60.10 --net 1:network=ops,ip=10.11.60.10 --net 2:network=prod,ip=10.12.60.10 --tags role:site-djh,env:site djh0.site.qxxxxxxxd.com
Mon Feb  1 11:17:51 2021  - INFO: Selected nodes for instance djh0.site.qxxxxxxxd.com via iallocator hail: dr64-zebra.site.qxxxxxxxd.com, dr64-camel.site.qxxxxxxxd.com
Mon Feb  1 11:17:51 2021  - INFO: NIC/0 inherits netparams ['br0', 'bridged', '']
Mon Feb  1 11:17:51 2021  - INFO: NIC/1 inherits netparams ['br11', 'bridged', '']
Mon Feb  1 11:17:51 2021  - INFO: NIC/2 inherits netparams ['br12', 'bridged', '']
Mon Feb  1 11:17:52 2021 * creating instance disks...
Mon Feb  1 11:17:58 2021 adding instance djh0.site.qxxxxxxxd.com to cluster config
Mon Feb  1 11:17:58 2021 adding disks to cluster config
Mon Feb  1 11:17:58 2021 * checking mirrors status
Mon Feb  1 11:17:58 2021  - INFO: - device disk/0:  1.10% done, 1m 41s remaining (estimated)
Mon Feb  1 11:17:58 2021 * checking mirrors status
Mon Feb  1 11:17:58 2021  - INFO: - device disk/0:  1.60% done, 1m 6s remaining (estimated)
Mon Feb  1 11:17:58 2021 * pausing disk sync to install instance OS
Mon Feb  1 11:17:59 2021 * running the instance OS create scripts...
Mon Feb  1 11:18:33 2021 * resuming disk sync
Failure: command execution error:
Could not add os for instance djh0.site.qxxxxxxxd.com on node dr64-zebra.site.qxxxxxxxd.com: OS create script failed (exited with exit code 127), sitet lines in the log file:
GPT:Primary header thinks Alt. header is not at the end of the disk.
GPT:Alternate GPT header not at the end of the disk.
GPT: Use GNU Parted to correct GPT errors.
GPT:Primary header thinks Alt. header is not at the end of the disk.
GPT:Alternate GPT header not at the end of the disk.
GPT: Use GNU Parted to correct GPT errors.
/usr/share/ganeti/os/nocloud/create: line 142: 1: command not found
/usr/share/ganeti/os/nocloud/create: line 143: 2_IP: command not found
```

I'm in a fork with changes to `kpartx` but the relevant lines are in `generate_network_config()` and appear to be right about here:
```
    for i in $(seq 0 $(expr $NIC_COUNT - 1)); do
        nic_ip=$(eval echo \$NIC_${i}_IP)
        [ -n "$nic_ip" -o $i = ${OSP_STATIC_HOST_INTERFACE:--1} ] || continue
        nic_mac=$(eval echo \$NIC_${i}_MAC)
```

**Comment by dannyman** [comment]
FWIW, this is what the relevant netplan looks like when revised manually:
```
network:
    ethernets:
        eth0:
            addresses:
            - 10.10.60.10/16
            gateway4: 10.10.0.1
            match:
                macaddress: aa:00:00:f1:f5:90
            nameservers:
                addresses:
                - 10.10.1.1
                search:
                - las.quantifind.com
        eth1:
            addresses:
            - 10.11.60.10/16
            match:
                macaddress: aa:00:00:89:26:39
        eth2:
            addresses:
            - 10.12.60.10/16
            match:
                macaddress: aa:00:00:bc:f4:1a
    version: 2
```
